### PR TITLE
FFWEB-2117: Fix error with export handler for FilterAttributes does not handle non-string values properly

### LINKED ISSUE #74: Export handler for FilterAttributes does not handle non-string values properly
https://github.com/FACT-Finder-Web-Components/oxid-eshop-module/blob/a8a53cc04da35762c26375aad9176197b55d442b/src/Export/Field/FilterAttributes.php#L42 is a bit problematic. 
I got this error in my instance a few times already: 
```PHP Fatal error:  Uncaught TypeError: Argument 1 passed to Omikron\FactFinder\Oxid\Export\Field\FilterAttributes::Omikron\FactFinder\Oxid\Export\Field\{closure}() must be of the type string, null given in /var/www/integration/20210708T125103/vendor/omikron/oxid-factfinder/src/Export/Field/FilterAttributes.php:38
Stack trace:
#0 [internal function]: Omikron\FactFinder\Oxid\Export\Field\FilterAttributes->Omikron\FactFinder\Oxid\Export\Field\{closure}()
#1 /var/www/integration/20210708T125103/vendor/omikron/oxid-factfinder/src/Export/Field/FilterAttributes.php(42): array_map()
#2 /var/www/integration/20210708T125103/vendor/omikron/oxid-factfinder/src/Export/Field/FilterAttributes.php(31): Omikron\FactFinder\Oxid\Export\Field\FilterAttributes->getVariantValues()
#3 /var/www/integration/20210708T125103/vendor/omikron/oxid-factfinder/src/Export/Entity/ArticleEntity.php(42): Omikron\FactFinder\Oxid\Export\Field\FilterAttributes->getValue()
#4 [internal function]: Omikron\FactFinder\Oxid\Export\Entity\ArticleEntity->Omikron\FactFinder in /var/www/integration/20210708T125103/vendor/omikron/oxid-factfinder/src/Export/Field/FilterAttributes.php on line 38
```
Admittedly this is due to corrupted data, but since this can seriously impact a shop as it will completely stop the FACT-Finder export from working, you should not rely on external code and data like this.

Remember, the getFieldData method of the OXID shop currently looks like this:
```
/**
 * Gets field data
 *
 * @param string $fieldName name (eg. 'oxtitle') of a data field to get
 *
 * @return mixed value of a data field
 */
public function getFieldData($fieldName)
{
    $longFieldName = $this->_getFieldLongName($fieldName);
    return ($this->$longFieldName instanceof Field) ? $this->$longFieldName->value : null;
}
```

So it can return anything. Including null

My proposal (even though it will degrade performance a little) is to either check those values and throw an error on null ***and continue with not impacted data rows***, force them to be '' on null or change your code to allow for null in other ways.

### PR DESCRIPTION
**Pull request by paulfcdd**
- Fixes
#74 
- Description: 
Fix error with export handler for FilterAttributes does not handle non-string values properly
- Tested with Oxid EShop editions/versions: 
6.2.4
- Tested with PHP versions: 
7.3

### CODE REVIEW

File: src/Export/Field/FilterAttributes.php [hunk 1]
```diff
@@ -39,7 +39,11 @@ protected function getVariantValues(Article $article, Article $parent): string
             return $this->filter->filterValue($key) . '=' . $this->filter->filterValue($value) . '|';
         }, ...array_map(function (string $value): array {
             return explode(' | ', $value);
-        }, [$parent->getFieldData('oxvarname'), $article->getFieldData('oxvarselect')])));
+        }, [
+                $parent->getFieldData('oxvarname') ? $parent->getFieldData('oxvarname') : 'missing field data',
```
Comment (paulfcdd) [inline src/Export/Field/FilterAttributes.php:43]: I'm not sure, should we return some information message or just empty string if getFieldData returns `null`

@a-laurowski

Comment (a-laurowski) [reply src/Export/Field/FilterAttributes.php:43]: i'd go with empty string, any other value will be evaluated by the FACT-Finder. We rather don't want to have a filter with option "missing field data" :D

File: src/Export/Field/FilterAttributes.php [hunk 2]
```diff
@@ -58,7 +62,7 @@ private function getSelectedFilterAttributes(Article $article): string
         $result = '';
         foreach (array_intersect_key(parent::getData($article), $this->getMultiAttributes()) as $key => $value) {
             if ($value) {
-                $result .= $this->filter->filterValue($key) . '=' . $this->filter->filterValue((string) $value) . '|';
+                $result .= $this->filter->filterValue($key) . '=' . $this->filter->filterValue((string)$value) . '|';
```
Comment (a-laurowski) [inline src/Export/Field/FilterAttributes.php:65]: can you add this space again? AFAIR we always have bee n using the spacing between value and casted types. Unless you know a PSR which tells different story

**Review by a-laurowski — CHANGES_REQUESTED** [review]
functionality-wise looks fine , missing changelog

File: CHANGELOG.md [hunk 3]
```diff
@@ -3,6 +3,9 @@
 ### Added
 - Introduced cart tracking using Web Components Javascript API
 
+### Fixed
+- Fix error with export handler which is does not handle non-string values properly
```
Comment (a-laurowski) [inline CHANGELOG.md:7]:
```suggestion
- Fix error with export handler which does not handle non-string values properly
```

**Review by a-laurowski — CHANGES_REQUESTED** [review]

File: CHANGELOG.md (hunk 3 above)
Comment (paulfcdd) [reply CHANGELOG.md:7]: english is my passion :D

**Review by a-laurowski — APPROVED** [review]
